### ISSUE TITLE
Update outdated translations for zh_cn and zh_tw

### ISSUE THREAD

**Issue by sboesen** [sboesen/langs#1]
I have updated settings_debuglevel and settings_debuglevel_desc in English (6ada807df0135e). I made minor changes to the Chinese versions but these should be rewritten to match the English version. PR greatly appreciated.

**Comment by FEI352** [comment]
#2 I don't quite understand GitHub. Is it correct to submit Pull requests like this? I have uploaded for a while now, but I noticed that you haven't merged them.

**Comment by sboesen** [comment]
Ah, sorry about that! I had notifications off on this repository. Apologies for the delay. Really appreciate you updating the translations, will merge.

**Comment by sboesen** [comment]
Merged. Thanks again! I turned notifications on* so I shouldn't miss future PRs :)
