### ISSUE TITLE
Add warning in Chinese to sync on remote changes / sync on launch compatibility

### ISSUE THREAD

**Issue by sboesen** [sboesen/langs#15]
Specifically this line:

https://github.com/sboesen/langs/commit/929c0c947bd03185c65231f3e946600945abd2d3

Should have the same warning (might not be compatible with each other) in Chinese for the `settings_autorun_desc` string in the other translation files.

**Comment by lyiton** [comment]
Pull requests submitted.

**Comment by sboesen** [comment]
Thank you! Closing.
